service: serverless-rest-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(./env.yml):${self:provider.stage}}

functions:
  createuser:
    handler: api/create.createUser
    events:
      - http:
          path: /create/user
          method: post
          cors: true

  createpost:
    handler: api/create.createPost
    events:
      - http:
          path: /create/post
          method: post
          cors: true

  createtag:
    handler: api/create.createTag
    events:
      - http:
          path: /create/tag
          method: post
          cors: true

  deleteUser:
    handler: api/delete.deleteUser
    events: 
      - http:
          path: /delete/user/{id}
          method: delete
          cors: true

  deletePost:
    handler: api/delete.deletePost
    events: 
      - http:
          path: /delete/post/{id}
          method: delete
          cors: true

  deleteTag:
    handler: api/delete.deleteTag
    events: 
      - http:
          path: /delete/tag/{id}
          method: delete
          cors: true

  updateUser:
    handler: api/update.updateUser
    events: 
      - http:
          path: /update/user/{id}
          method: put
          cors: true
  # updatePost:
  #   handler: api/update.updatePost
  #   events: 
  #     - http:
  #         path: /update/post/{id}
            # method: put
            # cors: true
  # updateTag:
  #   handler: api/update.updatePost
  #   events: 
  #     - http:
  #         path: /update/tag/{id}
  # getUser:
  #   handler: api/get.getUser
  #   events: 
  #     - http:
  #         path: /get/user/{id}
  # getPost:
  #   handler: api/get.getPost
  #   events: 
  #     - http:
  #         path: /get/post/{id}
  # getTag:
  #   handler: api/get.getPost
  #   events: 
  #     - http:
  #         path: /get/tag/{id}
  listUser:
    handler: api/list.listUser
    events: 
      - http:
          path: /list/user
          method: get
          cors: true
          
  listPost:
    handler: api/list.listPost
    events: 
      - http:
          path: /list/post
          method: get
          cors: true

  listTag:
    handler: api/list.listPost
    events: 
      - http:
          path: /list/tag
          method: get
          cors: true

custom:
  optimize:
    minify: true
    presets: ['env']

plugins:
  - serverless-plugin-optimize
  - serverless-offline