service: serverless-rest-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment: ${file(./env.yml):${self:provider.stage}}

functions:
  hello:
    handler: handler.hello

